name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "amoyxsat+openwrt@gmail.com"
        git config --global user.name "openwrt"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/xiaorouji/openwrt-passwall.git
        git fetch upstream

    - name: Checkout luci-smartdns-dev branch
      run: |
        git checkout -b luci-smartdns-dev origin/luci-smartdns-dev || git checkout luci-smartdns-dev

    - name: Merge upstream changes
      id: merge
      run: |
        if git merge upstream/luci-smartdns-dev --allow-unrelated-histories; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::conflict"
        fi

    - name: Handle Merge Conflicts
      if: steps.merge.outputs.status == 'conflict'
      run: |
        echo "Merge conflicts detected. Please resolve the conflicts manually."
        git status
        git diff > conflict_diff.txt
        exit 1

    - name: Upload Merge Conflict Diff
      if: steps.merge.outputs.status == 'conflict'
      uses: actions/upload-artifact@v2
      with:
        name: conflict_diff
        path: conflict_diff.txt

    - name: Push changes
      if: steps.merge.outputs.status == 'success'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/opamoy/openwrt-passwall.git luci-smartdns-dev
