name: SyncUpstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/xiaorouji/openwrt-passwall.git
        git fetch upstream

    - name: Checkout and update luci-smartdns-dev branch
      run: |
        # 切换到本地 luci-smartdns-dev 分支
        git checkout luci-smartdns-dev || git checkout -b luci-smartdns-dev
        # 拉取远程 origin 的最新更改并合并
        git pull origin luci-smartdns-dev --allow-unrelated-histories || true
        # 拉取并合并 upstream 的更改
        git merge upstream/luci-smartdns-dev --allow-unrelated-histories || true

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/opamoy/openwrt-passwall.git luci-smartdns-dev
